export const LandAbi = [
  {
    type: "event",
    name: "PlantLifetimeAssigned",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "plantId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "lifetime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newLifetime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlantPointsAssigned",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "plantId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "addedPoints",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newPlantPoints",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      {
        name: "from",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "to",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "value",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "VillageProductionClaimed",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "buildingId",
        type: "uint8",
        indexed: true,
        internalType: "uint8",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "VillageProductionXPClaimCooldownActive",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "buildingId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "currentTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "cooldownEndTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "VillageProductionXPClaimed",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "buildingId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "claimTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "xpAwarded",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "VillageSpeedUpWithSeed",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "buildingId",
        type: "uint8",
        indexed: true,
        internalType: "uint8",
      },
      {
        name: "speedUpCost",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "xp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "VillageUpgradedWithLeaf",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "buildingId",
        type: "uint8",
        indexed: true,
        internalType: "uint8",
      },
      {
        name: "upgradeCost",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "xp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "TownSpeedUpWithSeed",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "buildingId",
        type: "uint8",
        indexed: true,
        internalType: "uint8",
      },
      {
        name: "speedUpCost",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "xp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "TownUpgradedWithLeaf",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "buildingId",
        type: "uint8",
        indexed: true,
        internalType: "uint8",
      },
      {
        name: "upgradeCost",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "xp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "QuestStarted",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "farmerSlotId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "difficulty",
        type: "uint8",
        indexed: false,
        internalType: "enum QuestDifficultyLevel",
      },
      {
        name: "startBlock",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "endBlock",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "QuestCommitted",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "farmerSlotId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "pseudoRndBlock",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "QuestFinalized",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "farmerSlotId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "player",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "rewardType",
        type: "uint8",
        indexed: false,
        internalType: "enum RewardType",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "QuestReset",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "farmerSlotId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "player",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "LandMinted",
    inputs: [
      {
        name: "to",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "tokenId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "mintPrice",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "WareHouseLifetimeAssigned",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "plantId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "lifetime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newLifetime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "WareHousePlantPointsAssigned",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "plantId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "addedPoints",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newPlantPoints",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "LandNameChanged",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "name",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "function",
    name: "ownerOf",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  // Casino/Roulette Events
  {
    type: "event",
    name: "CasinoBuilt",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "builder",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "token",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "cost",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "RouletteSpinResult",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "player",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "winningNumber",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
      {
        name: "won",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "payout",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "RouletteBetExpired",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "player",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "forfeitedAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  // Blackjack Events
  {
    type: "event",
    name: "BlackjackResult",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "player",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "result",
        type: "uint8",
        indexed: false,
        internalType: "enum LibBlackjackStorage.GameResult",
      },
      {
        name: "playerFinalValue",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
      {
        name: "dealerFinalValue",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
      {
        name: "payout",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    outputs: [],
    anonymous: false,
  },
] as const; 