export const LandCasinoV2Abi = [
  {
    type: "event",
    name: "RouletteSpinResult",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "player",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "winningNumber",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
      {
        name: "won",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "payout",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "bettingToken",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "RouletteBetExpired",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "player",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "forfeitedAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "bettingToken",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "BlackjackBetPlaced",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "player",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "bettingToken",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "BlackjackResult",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "player",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "result",
        type: "uint8",
        indexed: false,
        internalType: "enum LibBlackjackStorage.GameResult",
      },
      {
        name: "playerFinalValue",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
      {
        name: "dealerFinalValue",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
      {
        name: "payout",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "bettingToken",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "BlackjackExpired",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "player",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "forfeitedAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "bettingToken",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    outputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "BlackjackGameComplete",
    inputs: [
      {
        name: "landId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "player",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "result",
        type: "uint8",
        indexed: false,
        internalType: "enum LibBlackjackStorage.GameResult",
      },
      {
        name: "playerCards",
        type: "uint8[]",
        indexed: false,
        internalType: "uint8[]",
      },
      {
        name: "splitCards",
        type: "uint8[]",
        indexed: false,
        internalType: "uint8[]",
      },
      {
        name: "dealerCards",
        type: "uint8[]",
        indexed: false,
        internalType: "uint8[]",
      },
      {
        name: "playerFinalValue",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
      {
        name: "splitFinalValue",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
      {
        name: "dealerFinalValue",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
      {
        name: "payout",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "bettingToken",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    outputs: [],
    anonymous: false,
  },
] as const;
